#
# MAINTAINER        Carson,C.J.Zeong <zcy@nicescale.com>
# DOCKER-VERSION    1.11.1
#
# Dockerizing logstash-forwarder: Dockerfile for building logstash-forwarder images
#
FROM       prima/filebeat
MAINTAINER Carson,C.J.Zeong <zcy@nicescale.com>

COPY filebeat.yml /filebeat.yml